### ISSUE TITLE
Comparision to other tools

### ISSUE THREAD

**Issue by mzfr** [Edu4rdSHL/fhc#3]
I am not sure if you have tried other tools like [httpx](https://github.com/projectdiscovery/httpx) which kind of does the same thing.
It would be nice if you can like to add a benchmark or maybe a comparision table of this tool with others.

Also I see that this is quite fast but do you plan to add some new features like showing the status code etc?

**Comment by Edu4rdSHL** [comment]
Here's an small one https://asciinema.org/a/IT4qsGI4y1q4BXBxujXP1kbyd. Please check [this tweet](https://twitter.com/edu4rdshl/status/1313678950544166913).

Edit: status codes support was added in https://github.com/Edu4rdSHL/fhc/releases/tag/0.4.0
