### ISSUE TITLE
64-bit versions of windows not supported

### ISSUE THREAD

**Issue by Mr-x2020** [Edu4rdSHL/fhc#6]
![image](https://user-images.githubusercontent.com/65666323/162737591-43e8bfe2-e0d9-4bc0-a20b-76080b0aa587.png)

**Comment by Edu4rdSHL** [comment]
Hello, thanks for the report. How are you running it?

**Comment by Mr-x2020** [comment]
from windows command line using precompiled fhc-windows.exe, how do you run it?

**Comment by Edu4rdSHL** [comment]
It's working correctly here. Please make sure that you have downloaded the correct version of FHC.

![image](https://user-images.githubusercontent.com/32582878/162767389-3da31e37-4acc-49a0-861b-27683b81c3e1.png)

**Comment by Mr-x2020** [comment]
I have text file with thousand of domains, how to do it with text file?

**Comment by Edu4rdSHL** [comment]
`type file.txt | fhc-windows.exe`

**Comment by Mr-x2020** [comment]
![image](https://user-images.githubusercontent.com/65666323/162942400-941463c7-5a5d-4e50-9f1b-4283587be4f5.png)

**Comment by Edu4rdSHL** [comment]
Please tell me the steps that you are following, I can not reproduce the issue:

![image](https://user-images.githubusercontent.com/32582878/162945139-b6d7b585-e719-454c-b9e2-984d01d3ad63.png)

**Comment by Mr-x2020** [comment]
It worked with version you provided in link in picture  , but not in latest releases

**Comment by Edu4rdSHL** [comment]
The version that I provided is the latest release, also the previous version works for me as well (I took the first screenshot while using it).

However, glad to hear that it's working.

**Comment by Mr-x2020** [comment]
thank you,
![image](https://user-images.githubusercontent.com/65666323/162948740-1a789a15-14ac-4eef-9bb1-53ab8f0a342f.png)
