### ISSUE TITLE
Probing issue!

### ISSUE THREAD

**Issue by blackcodersec** [Edu4rdSHL/fhc#9]
`https://support.hackerone.com/` this site is live. but `fhc` does not showing the domain.
is it possible to to auto redirect without `-L` argument?
and could you make a progress bar like total domain and process domain.

![image](https://github.com/Edu4rdSHL/fhc/assets/72689232/2a58c946-1ec9-42cd-bf4f-2981e83cbb68)

![image](https://github.com/Edu4rdSHL/fhc/assets/72689232/c2512651-c22b-4287-b4fc-9ca9bc8b45c7)

**Comment by Edu4rdSHL** [comment]
Hello, thanks for the report. I will look into it.

**Comment by Edu4rdSHL** [comment]
Hello, after more testing, it seems to be an issue with the domain itself. If I run `curl -L https://support.hackerone.com`, I get:

```
$ curl -L https://support.hackerone.com
curl: (47) Maximum (50) redirects followed
```
Which is what the tool is facing. The current workaround is to disable redirects, that way the tool will simply perform a check and see if it replies to http/https without doing anything else.
